"""Tests for the repo's shell scripts (pick_icon.sh), run for real with `bash`.

A stub `python3` placed first on PATH stands in for the icon scripts: it records its cwd and
arguments in $STUB_LOG and exits with $STUB_EXIT, so no icon script, browser or network runs.
"""
import os
import shutil
import subprocess
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
PICK_ICON = os.path.join(REPO_ROOT, "pick_icon.sh")
BASH = shutil.which("bash")

pytestmark = pytest.mark.skipif(BASH is None, reason="bash not installed")

STUB = """#!{bash}
{{
  pwd
  for arg in "$@"; do printf '%s\\n' "$arg"; done
}} > "$STUB_LOG"
exit "${{STUB_EXIT:-0}}"
"""


@pytest.fixture
def stub(tmp_path):
    """A bin dir holding the fake python3; returns a runner for pick_icon.sh."""
    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    python3 = bin_dir / "python3"
    python3.write_text(STUB.format(bash=BASH))
    python3.chmod(0o755)
    log = tmp_path / "python3.log"

    class Stub:
        def run(self, *args, exit_code=0, cwd=None, script=PICK_ICON, path=None):
            env = {
                "PATH": path if path is not None else f"{bin_dir}{os.pathsep}{os.environ.get('PATH', '')}",
                "STUB_LOG": str(log),
                "STUB_EXIT": str(exit_code),
            }
            return subprocess.run(
                [BASH, script, *args], cwd=cwd or tmp_path, env=env, capture_output=True, text=True, timeout=30,
            )

        def call(self):
            """(cwd, argv) the fake python3 was started with, or None if it never ran."""
            if not log.exists():
                return None
            lines = log.read_text().splitlines()
            return lines[0], lines[1:]

    return Stub()


def test_runs_the_picker_with_gui_web_and_forwards_arguments(stub):
    result = stub.run("--config", "some dir/config.json")

    assert result.returncode == 0, result.stdout + result.stderr
    _, argv = stub.call()
    assert argv == [
        os.path.join(REPO_ROOT, "icons", "scripts", "master_icon.py"), "--gui-web", "--config", "some dir/config.json",
    ]
    assert "Selection complete!" in result.stdout


def test_propagates_a_failing_exit_status(stub):
    """Regression: a failing master_icon.py still printed "Selection complete!" and exited 0."""
    result = stub.run(exit_code=3)

    assert result.returncode == 3
    assert "Selection complete!" not in result.stdout
    assert "failed (exit 3)" in result.stdout


def test_works_from_another_directory_and_keeps_the_callers_cwd(stub, tmp_path):
    """Regression: the script only found icons/scripts/master_icon.py from the repo root."""
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()

    result = stub.run(cwd=elsewhere)

    assert result.returncode == 0, result.stdout + result.stderr
    cwd, argv = stub.call()
    assert cwd == str(elsewhere)  # relative arguments keep meaning the caller's directory
    assert os.path.isfile(argv[0])
    assert argv[0] == os.path.join(REPO_ROOT, "icons", "scripts", "master_icon.py")


def test_works_when_called_by_a_relative_path(stub):
    result = stub.run(cwd=os.path.dirname(REPO_ROOT), script=os.path.join(os.path.basename(REPO_ROOT), "pick_icon.sh"))

    assert result.returncode == 0, result.stdout + result.stderr
    _, argv = stub.call()
    assert argv[0] == os.path.join(REPO_ROOT, "icons", "scripts", "master_icon.py")


def test_without_python3_exits_1_with_an_error(stub, tmp_path):
    only_dirname = tmp_path / "no-python"
    only_dirname.mkdir()
    (only_dirname / "dirname").symlink_to(shutil.which("dirname"))

    result = stub.run(path=str(only_dirname))

    assert result.returncode == 1
    assert "Python 3 not found" in result.stdout
    assert stub.call() is None


def test_pick_icon_is_executable():
    assert os.access(PICK_ICON, os.X_OK)


# ---------------------------------------------------------------------------------------------
# shellcheck on every tracked shell script
# ---------------------------------------------------------------------------------------------


def _shellcheck_command():
    """shellcheck from this interpreter's environment (shellcheck-py) if installed, else PATH."""
    local = os.path.join(os.path.dirname(sys.executable), "shellcheck")
    return local if os.path.exists(local) else shutil.which("shellcheck")


def _tracked_shell_scripts():
    result = subprocess.run(["git", "ls-files", "*.sh"], cwd=REPO_ROOT, capture_output=True, text=True)
    if result.returncode != 0:
        pytest.skip("not a git checkout")
    # gradlew has no .sh extension and is generated by Gradle, so it is never listed here.
    return result.stdout.split()


def test_shell_scripts_pass_shellcheck():
    shellcheck = _shellcheck_command()
    if shellcheck is None:
        pytest.skip("shellcheck not installed (pip install -r icons/requirements-dev.txt)")
    scripts = _tracked_shell_scripts()
    assert "pick_icon.sh" in scripts

    result = subprocess.run([shellcheck, *scripts], cwd=REPO_ROOT, capture_output=True, text=True)

    assert result.returncode == 0, result.stdout + result.stderr
